import Head from "next/head";
import React from "react";
import Card from "../Card/Card";
import Footer from "../Footer/Footer";
import Navbar from "../Navbar/Navbar";

const Container = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className="flex flex-col md:flex-row m-5 items-center justify-center">
      <Card/>
      <Card/>
      </div>
      {children}
      <Footer />
    </div>
  );
};

export default Container;
